#ifndef GENERATED_ASN1SCC_Context_joystick_2_joint_commands_H
#define GENERATED_ASN1SCC_Context_joystick_2_joint_commands_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccT_Double max_rotation_speed;
    asn1SccT_Int8 rotation_axis;
} asn1SccContext_joystick_2_joint_commands;

flag asn1SccContext_joystick_2_joint_commands_Equal(const asn1SccContext_joystick_2_joint_commands* pVal1, const asn1SccContext_joystick_2_joint_commands* pVal2);

void asn1SccContext_joystick_2_joint_commands_Initialize(asn1SccContext_joystick_2_joint_commands* pVal);

#define ERR_CONTEXT_JOYSTICK_2_JOINT_COMMANDS_MAX_ROTATION_SPEED		1  /**/
#define ERR_CONTEXT_JOYSTICK_2_JOINT_COMMANDS_ROTATION_AXIS		12  /**/
flag asn1SccContext_joystick_2_joint_commands_IsConstraintValid(const asn1SccContext_joystick_2_joint_commands* pVal, int* pErrCode);

extern const asn1SccContext_joystick_2_joint_commands joystick_2_joint_commands_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif