#ifndef GENERATED_ASN1SCC_Context_joystick_2_lights_H
#define GENERATED_ASN1SCC_Context_joystick_2_lights_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_joystick_2_lights --------------------------------------------*/

typedef struct {
    asn1SccT_Int8 white_light_button;
    asn1SccT_Int8 uv_light_button;
    asn1SccT_Int8 point_turn_button;

} asn1SccContext_joystick_2_lights;

flag asn1SccContext_joystick_2_lights_Equal(const asn1SccContext_joystick_2_lights* pVal1, const asn1SccContext_joystick_2_lights* pVal2);

void asn1SccContext_joystick_2_lights_Initialize(asn1SccContext_joystick_2_lights* pVal);

#define ERR_CONTEXT_JOYSTICK_2_LIGHTS_WHITE_LIGHT_BUTTON		1  /**/
#define ERR_CONTEXT_JOYSTICK_2_LIGHTS_UV_LIGHT_BUTTON		12  /**/
#define ERR_CONTEXT_JOYSTICK_2_LIGHTS_POINT_TURN_BUTTON		23  /**/
flag asn1SccContext_joystick_2_lights_IsConstraintValid(const asn1SccContext_joystick_2_lights* pVal, int* pErrCode);

extern const asn1SccContext_joystick_2_lights joystick_2_lights_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif