#ifndef GENERATED_ASN1SCC_Context_controldevice_H
#define GENERATED_ASN1SCC_Context_controldevice_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccT_UInt16 device_number;
} asn1SccContext_controldevice;

flag asn1SccContext_controldevice_Equal(const asn1SccContext_controldevice* pVal1, const asn1SccContext_controldevice* pVal2);

void asn1SccContext_controldevice_Initialize(asn1SccContext_controldevice* pVal);

#define ERR_CONTEXT_CONTROLDEVICE_DEVICE_NUMBER		1  /**/
flag asn1SccContext_controldevice_IsConstraintValid(const asn1SccContext_controldevice* pVal, int* pErrCode);

extern const asn1SccContext_controldevice controldevice_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif