/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-controldevice.h"


const asn1SccContext_controldevice controldevice_ctxt = {
    .device_number = 1
};


flag asn1SccContext_controldevice_Equal(const asn1SccContext_controldevice* pVal1, const asn1SccContext_controldevice* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->device_number == pVal2->device_number);

	return ret;

}

void asn1SccContext_controldevice_Initialize(asn1SccContext_controldevice* pVal)
{


	/*set device_number */
	asn1SccT_UInt16_Initialize((&(pVal->device_number)));
}

flag asn1SccContext_controldevice_IsConstraintValid(const asn1SccContext_controldevice *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = (pVal->device_number <= 65535UL);
    *pErrCode = ret ? 0 :  ERR_CONTEXT_CONTROLDEVICE_DEVICE_NUMBER;

	return ret;
}

