/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-joystick-2-motion-command.h"


const asn1SccContext_joystick_2_motion_command joystick_2_motion_command_ctxt = {
    .max_rotation_speed = 9.00000000000000000000E+001,
    .max_translation_speed = 1.00000000000000000000E-002,
    .translation_axis = 1,
    .rotation_axis = 0
};


flag asn1SccContext_joystick_2_motion_command_Equal(const asn1SccContext_joystick_2_motion_command* pVal1, const asn1SccContext_joystick_2_motion_command* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->max_rotation_speed == pVal2->max_rotation_speed);

    if (ret) {
        ret = (pVal1->max_translation_speed == pVal2->max_translation_speed);

        if (ret) {
            ret = (pVal1->translation_axis == pVal2->translation_axis);

            if (ret) {
                ret = (pVal1->rotation_axis == pVal2->rotation_axis);

            }
        }
    }
	return ret;

}

void asn1SccContext_joystick_2_motion_command_Initialize(asn1SccContext_joystick_2_motion_command* pVal)
{


	/*set max_rotation_speed */
	asn1SccT_Double_Initialize((&(pVal->max_rotation_speed)));
	/*set max_translation_speed */
	asn1SccT_Double_Initialize((&(pVal->max_translation_speed)));
	/*set translation_axis */
	asn1SccT_Int8_Initialize((&(pVal->translation_axis)));
	/*set rotation_axis */
	asn1SccT_Int8_Initialize((&(pVal->rotation_axis)));
}

flag asn1SccContext_joystick_2_motion_command_IsConstraintValid(const asn1SccContext_joystick_2_motion_command *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = ((-1.79769313486231570000E+308 <= pVal->max_rotation_speed) && (pVal->max_rotation_speed <= 1.79769313486231570000E+308));
    *pErrCode = ret ? 0 :  ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_MAX_ROTATION_SPEED;
    if (ret) {
        ret = ((-1.79769313486231570000E+308 <= pVal->max_translation_speed) && (pVal->max_translation_speed <= 1.79769313486231570000E+308));
        *pErrCode = ret ? 0 :  ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_MAX_TRANSLATION_SPEED;
        if (ret) {
            ret = ((-128LL <= pVal->translation_axis) && (pVal->translation_axis <= 127LL));
            *pErrCode = ret ? 0 :  ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_TRANSLATION_AXIS;
            if (ret) {
                ret = ((-128LL <= pVal->rotation_axis) && (pVal->rotation_axis <= 127LL));
                *pErrCode = ret ? 0 :  ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_ROTATION_AXIS;
            }
        }
    }

	return ret;
}

