#ifndef GENERATED_ASN1SCC_Context_joystick_2_motion_command_H
#define GENERATED_ASN1SCC_Context_joystick_2_motion_command_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccT_Double max_rotation_speed;
    asn1SccT_Double max_translation_speed;
    asn1SccT_Int8 translation_axis;
    asn1SccT_Int8 rotation_axis;
} asn1SccContext_joystick_2_motion_command;

flag asn1SccContext_joystick_2_motion_command_Equal(const asn1SccContext_joystick_2_motion_command* pVal1, const asn1SccContext_joystick_2_motion_command* pVal2);

void asn1SccContext_joystick_2_motion_command_Initialize(asn1SccContext_joystick_2_motion_command* pVal);

#define ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_MAX_ROTATION_SPEED		1  /**/
#define ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_MAX_TRANSLATION_SPEED		12  /**/
#define ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_TRANSLATION_AXIS		23  /**/
#define ERR_CONTEXT_JOYSTICK_2_MOTION_COMMAND_ROTATION_AXIS		34  /**/
flag asn1SccContext_joystick_2_motion_command_IsConstraintValid(const asn1SccContext_joystick_2_motion_command* pVal, int* pErrCode);

extern const asn1SccContext_joystick_2_motion_command joystick_2_motion_command_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif